plugins {
    id 'com.android.application'
}

android {
    compileSdk 34
    namespace 'com.volumecontrol'

    defaultConfig {
        applicationId "com.volumecontrol"
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName "2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            applicationIdSuffix ""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
